const SET_IS_ADMIN = 'SET_IS_ADMIN';
const SET_EMAIL = 'SET_EMAIL';
const SET_TOURNAMENT = 'SET_TOURNAMENT';
const SET_EVENT_DATE = 'SET_EVENT_DATE';
const SET_YEARS = 'SET_YEARS';
const SET_CREDENTIALS = 'SET_CREDENTIALS';

export default {
	SET_IS_ADMIN,
	SET_EMAIL,
	SET_TOURNAMENT,
	SET_EVENT_DATE,
	SET_YEARS,
	SET_CREDENTIALS,
};